name: Hello-world
on: workflow_dispatch
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps: 
      - name: hello step
        run: |
          echo " this is line one"
          echo " this is line two"
  hello-world-two:
    runs-on: ubuntu-latest
    needs: hello-world
    steps: 
      - name: hello step
        run: |
          echo " this is line sample one"
          echo " this is line sample two"
